/**
 * dsh-fleet-plugin — the DeepSeek Harness bundle Node half.
 *
 * Contract (official bundle form):
 *  - named-exports `name` / `inject` / `apply` → a complete Cordis plugin;
 *  - config file `$DSH_HOME/dsh-fleet.json` (edited through the API below or
 *    the client settings card);
 *  - generates `$DSH_HOME/dsh-fleet/frpc.toml` from the config and supervises
 *    frpc (exponential-backoff restart, dispose on plugin stop);
 *  - serves the read-only metrics protocol at `/dsh-status` (CORS open — the
 *    hub portal page reads it cross-origin; never carries credentials);
 *  - serves `/api/dsh-fleet/config` + `/api/dsh-fleet/status` for the client
 *    settings card. The config route redacts the token on reads and only
 *    replaces it on writes when a non-redacted value is sent.
 *
 * Every route is additive and gated: presence of `webServer` is probed
 * non-strictly (a strict probe can silently skip the routes when the
 * webserver fiber activates late — the octie 404 lesson, TROUBLESHOOTING).
 */
import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, statfsSync, writeFileSync } from 'node:fs';
import { arch, cpus, freemem, hostname, homedir, platform, totalmem, uptime } from 'node:os';
import { join } from 'node:path';

export const name = 'dsh-fleet';
export const inject = [];

const FLEET_VERSION = '0.1.0';
const CONFIG_FILE = () => join(process.env.DSH_HOME || join(homedir(), '.dsh'), 'dsh-fleet.json');
const FRPC_CFG_FILE = () => join(process.env.DSH_HOME || join(homedir(), '.dsh'), 'dsh-fleet', 'frpc.toml');

function defaultFrpcPath() {
  const bin = platform() === 'win32' ? 'frpc.exe' : 'frpc';
  return join(homedir(), '.dsh-fleet', 'frpc-0.71.0', bin);
}

const DEFAULTS = {
  enabled: true,
  manageFrpc: true,
  nodeName: hostname(),
  hubUrl: '',
  token: '',
  slug: '',
  port: '6101',
  frpcPath: '',
  restartBackoffSec: 5,
};

function loadConfig() {
  try {
    return { ...DEFAULTS, ...JSON.parse(readFileSync(CONFIG_FILE(), 'utf8')) };
  } catch {
    return { ...DEFAULTS };
  }
}

function saveConfig(config) {
  mkdirSync(join(CONFIG_FILE(), '..'), { recursive: true });
  writeFileSync(CONFIG_FILE(), JSON.stringify(config, null, 2) + '\n');
}

const TOKEN_RE = /^[0-9a-f]{32}$/i;
const SLUG_RE = /^[a-z0-9][a-z0-9-]{1,62}$/;
const PORT_RE = /^(6[1-9][0-9]{2})$/;

function redact(token) {
  if (typeof token !== 'string' || token.length <= 4) return '';
  return '****' + token.slice(-4);
}

function frpcToml(config, frpcPath) {
  const hub = String(config.hubUrl || '').includes(':')
    ? String(config.hubUrl).split(':') : [String(config.hubUrl || ''), '7000'];
  return [
    '# dsh-fleet frpc config — generated by the dsh-fleet-plugin Node half.',
    '# Edit through the DSH settings card (Fleet) or $DSH_HOME/dsh-fleet.json.',
    `serverAddr = "${hub[0]}"`,
    `serverPort = ${hub[1]}`,
    'auth.method = "token"',
    `auth.token = "${config.token}"`,
    'transport.tls.enable = true',
    '',
    '[[proxies]]',
    `name = "${config.slug}"`,
    'type = "tcp"',
    'localIP = "127.0.0.1"',
    'localPort = 3080',
    `remotePort = ${config.port}`,
    '',
  ].join('\n');
}

/** Two-sample CPU busy ratio (Windows loadavg() is always 0 — measured fact). */
function makeCpuSampler() {
  let prev = null;
  let prevTime = 0;
  return () => {
    const now = Date.now();
    const cur = cpus();
    if (prev === null || prevTime === 0) { prev = cur; prevTime = now; return null; }
    let prevBusy = 0; let prevTotal = 0; let curBusy = 0; let curTotal = 0;
    for (const t of prev) { prevBusy += t.times.user + t.times.nice + t.times.sys + t.times.irq; prevTotal += prevBusy + t.times.idle; }
    for (const t of cur) { curBusy += t.times.user + t.times.nice + t.times.sys + t.times.irq; curTotal += curBusy + t.times.idle; }
    prev = cur; prevTime = now;
    const busy = curBusy - prevBusy; const total = curTotal - prevTotal;
    return total > 0 ? Math.max(0, Math.min(100, (busy / total) * 100)) : null;
  };
}

function systemSnapshot(cpuSample) {
  const disk = (() => {
    try {
      const s = statfsSync(homedir());
      return { diskTotal: s.bsize * s.blocks, diskFree: s.bsize * s.bavail };
    } catch { return { diskTotal: 0, diskFree: 0 }; }
  })();
  return {
    os: `${platform()}/${arch()}`,
    hostname: hostname(),
    uptimeSec: Math.round(uptime()),
    cpus: cpus().length,
    cpuLoadPct: cpuSample(),
    memTotal: totalmem(),
    memFree: freemem(),
    ...disk,
    sampleAt: new Date().toISOString(),
  };
}

function dshStatus(config, cpuSample) {
  return {
    ok: true,
    node: { name: config.nodeName, slug: config.slug, fleetVersion: FLEET_VERSION },
    system: systemSnapshot(cpuSample),
  };
}

export function apply(ctx) {
  const disposers = [];
  const sample = makeCpuSampler();
  let config = loadConfig();

  // ── frpc supervision (exponential backoff) ──────────────────────────────
  const sup = {
    child: null,
    running: false,
    online: false,
    restarts: 0,
    lastError: '',
    buffer: '',
  };
  let backoffTimer = null;

  function note(data) {
    sup.buffer = (sup.buffer + String(data)).slice(-8192);
    if (!sup.online && sup.buffer.includes('login to server success')) sup.online = true;
    if (sup.buffer.includes('token in login doesn') || sup.buffer.includes('auth failed')) {
      sup.lastError = 'the hub rejected this token (revoked or wrong)';
    }
  }

  function stopSupervisor() {
    if (backoffTimer) { clearTimeout(backoffTimer); backoffTimer = null; }
    if (sup.child) {
      sup.child.removeAllListeners();
      try { sup.child.kill(); } catch { /* already gone */ }
      sup.child = null;
    }
    sup.running = false;
    sup.online = false;
  }

  function startSupervisor() {
    stopSupervisor();
    if (!config.enabled || !config.manageFrpc) return;
    const bin = config.frpcPath || defaultFrpcPath();
    if (!existsSync(bin)) { sup.lastError = `frpc binary not found at ${bin} — run node-bootstrap first`; return; }
    const cfgFile = FRPC_CFG_FILE();
    mkdirSync(join(cfgFile, '..'), { recursive: true });
    writeFileSync(cfgFile, frpcToml(config));
    sup.buffer = '';
    const child = spawn(bin, ['-c', cfgFile], { stdio: ['ignore', 'pipe', 'pipe'] });
    sup.child = child;
    sup.running = true;
    child.stdout.on('data', note);
    child.stderr.on('data', note);
    child.on('error', (err) => { sup.lastError = String(err && err.message || err); });
    child.on('exit', (code) => {
      if (sup.child !== child) return; // already replaced
      sup.running = false;
      sup.online = false;
      if (!config.enabled || !config.manageFrpc) return; // intentional stop
      sup.restarts += 1;
      const base = Math.max(1, Number(config.restartBackoffSec) || 5);
      const delay = Math.min(base * (2 ** Math.min(sup.restarts - 1, 3)), 60) * 1000;
      sup.lastError = `frpc exited (code ${code}) at ${new Date().toISOString()} — restarting in ${delay / 1000}s`;
      backoffTimer = setTimeout(startSupervisor, delay);
    });
  }

  function reloadFromConfig(next) {
    config = { ...config, ...next };
    saveConfig(config);
    startSupervisor();
  }

  // ── web routes (headless-safe, non-strict probe) ────────────────────────
  function json(res, data, status = 200, extraHeaders = {}) {
    res.writeHead(status, { 'Content-Type': 'application/json', ...extraHeaders });
    res.end(JSON.stringify(data));
  }

  function readBody(req, limit = 64 * 1024) {
    return new Promise((resolve, reject) => {
      let size = 0;
      const chunks = [];
      req.on('data', (chunk) => {
        size += chunk.length;
        if (size > limit) { reject(new Error('body too large')); req.destroy(); return; }
        chunks.push(chunk);
      });
      req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
      req.on('error', reject);
    });
  }

  function registerWebRoutes(webServer) {
    disposers.push(webServer.register({
      kind: 'exact',
      path: '/dsh-status',
      handler: (_req, res) => {
        try {
          json(res, dshStatus(config, sample), 200, { 'Access-Control-Allow-Origin': '*' });
        } catch (err) { json(res, { ok: false, error: String(err && err.message || err) }, 500); }
      },
    }));

    disposers.push(webServer.register({
      kind: 'exact',
      path: '/api/dsh-fleet/config',
      handler: async (req, res) => {
        try {
          if (req.method === 'POST') {
            const body = JSON.parse((await readBody(req)) || '{}');
            const next = {};
            if (typeof body.enabled === 'boolean') next.enabled = body.enabled;
            if (typeof body.manageFrpc === 'boolean') next.manageFrpc = body.manageFrpc;
            if (typeof body.nodeName === 'string' && body.nodeName.trim()) next.nodeName = body.nodeName.trim().slice(0, 64);
            if (typeof body.hubUrl === 'string' && body.hubUrl.trim()) next.hubUrl = body.hubUrl.trim().slice(0, 253);
            if (typeof body.slug === 'string') {
              if (!SLUG_RE.test(body.slug)) throw new Error('slug must match [a-z0-9][a-z0-9-]{1,62}');
              next.slug = body.slug;
            }
            if (typeof body.port === 'string') {
              if (!PORT_RE.test(body.port)) throw new Error('port must be within the hub pool 6101-6199');
              next.port = body.port;
            }
            if (typeof body.frpcPath === 'string' && body.frpcPath.trim()) next.frpcPath = body.frpcPath.trim();
            if (typeof body.restartBackoffSec === 'number' && body.restartBackoffSec >= 1) next.restartBackoffSec = body.restartBackoffSec;
            if (typeof body.token === 'string' && body.token !== '' && !body.token.startsWith('****')) {
              if (!TOKEN_RE.test(body.token)) throw new Error('token must be 32 hex chars (from hub enroll)');
              next.token = body.token;
            }
            reloadFromConfig(next);
            return json(res, publicConfig());
          }
          json(res, publicConfig());
        } catch (err) {
          json(res, { error: String(err && err.message || err) }, 400);
        }
      },
    }));

    disposers.push(webServer.register({
      kind: 'exact',
      path: '/api/dsh-fleet/status',
      handler: (_req, res) => {
        const configured = Boolean(config.hubUrl && config.token && config.slug);
        json(res, {
          enabled: Boolean(config.enabled),
          manageFrpc: Boolean(config.manageFrpc),
          nodeName: config.nodeName,
          slug: config.slug,
          hubUrl: config.hubUrl,
          configured,
          frpcRunning: sup.running,
          tunnelOnline: sup.online,
          restarts: sup.restarts,
          lastError: sup.lastError,
        });
      },
    }));
  }

  function publicConfig() {
    return { ...config, token: redact(config.token) };
  }

  // Order-robustness: when the webserver is not yet PROVIDED at apply time
  // (a profile lists this bundle before dsh-web-app), the optional-inject
  // form registers the routes the moment it appears, and tears nothing down
  // when it never does (headless). Same pattern as dsh-settings. Registered
  // per service INSTANCE, so a reloaded webserver re-registers cleanly.
  let registeredFor = null;
  const registerFor = (ws) => {
    if (ws === undefined || ws === registeredFor || typeof ws.register !== 'function') return;
    registeredFor = ws;
    registerWebRoutes(ws);
  };
  registerFor(ctx.get('webServer', false));
  ctx.inject(['webServer'], (wsCtx) => {
    registerFor(wsCtx.get('webServer'));
  });

  startSupervisor();

  ctx.effect(() => () => {
    for (const dispose of disposers) { try { dispose(); } catch { /* best-effort */ } }
    stopSupervisor();
  }, 'dsh-fleet: routes + frpc supervision');
}
