# dsh-fleet node frpc config — generated by node-bootstrap.mjs, do not edit.
serverAddr = "__HUB_HOST__"
serverPort = 7000

# Per-node credential issued by `hub enroll <slug>` (revocable server-side).
auth.method = "token"
auth.token = "__TOKEN__"

# Encrypt the control channel to the hub.
transport.tls.enable = true

[[proxies]]
name = "__SLUG__"          # the hub portal lists proxies by this name
type = "tcp"
localIP = "127.0.0.1"
localPort = 3080           # the node's DSH web GUI
remotePort = __PORT__      # hub-assigned port (Caddy reverse-proxies it)
