# dsh-fleet Caddy base fragment — generated by hub-setup.sh from this template.
# Node subdomain blocks live as separate 10-<slug>.caddy fragments in the same
# directory (appended by `hub enroll`) and are NOT touched by hub-setup re-runs.

# ── Portal ──────────────────────────────────────────────────────────────────
hub.__DOMAIN__:8443 {
	tls {
		dns __DNS_PROVIDER__ {env.__DNS_ENV_ID__} {env.__DNS_ENV_KEY__}
	}

	# Deployment-level single password (bcrypt hash generated at setup time).
	basic_auth {
		fleet __PORTAL_PW_HASH__
	}

	# frps dashboard, server-side auth injection only.
	handle /fleet/api/* {
		reverse_proxy 127.0.0.1:7500 {
			header_up Authorization "Basic {env.FRPS_DASHBOARD_AUTH}"
		}
	}

	# Fleet portal static page.
	handle {
		root * /var/www/fleet-portal
		file_server
	}
}

# ── Unassigned subdomains: authenticated 404 (specific <slug> blocks win) ──
*.__DOMAIN__:8443 {
	tls {
		dns __DNS_PROVIDER__ {env.__DNS_ENV_ID__} {env.__DNS_ENV_KEY__}
	}

	basic_auth {
		fleet __PORTAL_PW_HASH__
	}

	respond "no such fleet node" 404
}
