# fleet-tls-mode: __TLS_MODE__
# fleet-tls-env-id: __DNS_ENV_ID__
# fleet-tls-env-key: __DNS_ENV_KEY__
# dsh-fleet Caddy base fragment — generated by hub-setup.sh from this template.
# Node subdomain blocks live as separate 10-<slug>.caddy fragments in the same
# directory (appended by `hub enroll`) and are NOT touched by hub-setup re-runs.

# ── Portal ──────────────────────────────────────────────────────────────────
hub.__DOMAIN__:8443 {
__TLS_BLOCK__

	# Deployment-level single password (bcrypt hash generated at setup time).
	basic_auth {
		fleet __PORTAL_PW_HASH__
	}

	# frps dashboard, server-side auth injection only.
	handle /fleet/api/* {
		reverse_proxy 127.0.0.1:7500 {
			header_up Authorization "Basic {env.FRPS_DASHBOARD_AUTH}"
		}
	}

	# Fleet portal static page.
	handle {
		root * /var/www/fleet-portal
		file_server
	}
}

# ── Unassigned subdomains: authenticated 404 (specific <slug> blocks win) ──
# Only rendered in DNS-01 tls modes — wildcard certs CANNOT be issued via
# HTTP-01, so http mode drops this block and unassigned subdomains simply
# fail to connect (arguably safer). hub-setup strips this section in http mode.
# __WILDCARD_BEGIN__
*.__DOMAIN__:8443 {
__TLS_BLOCK__

	basic_auth {
		fleet __PORTAL_PW_HASH__
	}

	respond "no such fleet node" 404
}
# __WILDCARD_END__
