# dsh-fleet frps server config — generated by hub-setup.sh from this template.
# Hand-edits are lost on `hub-setup.sh --force` re-runs; use the token file
# below for per-node credentials (managed by `hub enroll` / `hub revoke`).

bindPort = 7000

# Per-node credentials: one token per line in the tokenSource file.
# hub enroll appends a line; hub revoke removes it and reloads frps.
auth.method = "token"
auth.tokenSource = "/etc/frp/tokens"

# Encrypt the control channel between every frpc and this frps.
transport.tls.force = true

# Admin dashboard: loopback only. The portal proxies it to the browser with
# server-side injected credentials — the browser never sees frps credentials.
webServer.addr = "127.0.0.1"
webServer.port = 7500
webServer.user = "fleet-admin"
webServer.password = "__DASHBOARD_PASSWORD__"
